name: Build

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Grant execute permission
        run: chmod +x gradlew
      
      - name: Build Plugin
        run: |
          ./gradlew make
          
      - name: Push builds
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone --branch=builds --single-branch "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" builds
          cd builds
          git rm -rf .
          cp -r ../build/repos/* .
          git add .
          git commit -m "Build ${{ github.sha }}" || exit 0
          git push
